site_name: pgrest
site_url: https://anand2312.github.io/pgrest
site_description: Documentation for pgrest.
site_author: anand2312

theme:
  features:
    - navigation.top
  name: "material"
  palette:
    - scheme: slate
      primary: pink
      toggle:
        icon: material/eye-outline
        name: Switch to light mode
    - scheme: default
      primary: pink
      toggle:
        icon: material/eye
        name: Switch to dark mode
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Changelog: changelog.md
  - Examples:
      - Queries:
          - Simple-style Queries: examples/queries/simple-queries.md
          - Filter-style Queries: examples/queries/filter-queries.md
  - API Reference:
      - Client: reference/client.md
      - Query Builders: reference/builders.md
      - Column: reference/query.md
      - Exceptions: reference/exceptions.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_root_heading: true
            members_order: "source"

repo_name: anand2312/pgrest-client
repo_url: https://github.com/anand2312/pgrest-client

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "#"
