# This project uses Poetry for dependency management
# However, we also use Cloudflare Pages for preview deployments of documentation
# CF pages needs a requirements.txt file to read from.
# This file exists ONLY for the documentation deploy process
# Regular users will install based on the poetry.lock file.

name: Make requirements.txt

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"
  pull_request:
    branches:
      - main
    paths:
      - "pyproject.toml"

jobs:
  make-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: poetry install
      - name: Add Documentation Dependencies
        run: poetry add mkdocs-material mkdocstrings # not as dev-deps; as poetry export doesn't include them
      - name: Export requirements file
        run: poetry export --output requirements.txt
      - name: Setup git
        run: |
          git config user.name "CI Bot"
          git config user.email "<>"
      - name: Commit and Push
        run: |
          git add requirements.txt
          git commit -m "docs(cf-preview): Update requirements.txt"
          git push origin main
